// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDoOq5u0gva0ETKKNNA3vEb048u6p9H4KM',
    appId: '1:770986243442:web:e283c9a45628efb4f919eb',
    messagingSenderId: '770986243442',
    projectId: 'more-pic',
    authDomain: 'more-pic.firebaseapp.com',
    storageBucket: 'more_pick',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9WKU65Qdj5WvA_33ooxXqJXrU0efJKtw',
    appId: '1:770986243442:android:3843deefeda80ecaf919eb',
    messagingSenderId: '770986243442',
    projectId: 'more-pic',
    storageBucket: 'more_pick',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9sHrv9-SR6iYGmMz027LZvmSOSisz1Bk',
    appId: '1:770986243442:ios:621abbb09e33185cf919eb',
    messagingSenderId: '770986243442',
    projectId: 'more-pic',
    storageBucket: 'more_pick',
    iosBundleId: 'com.example.morePic',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA9sHrv9-SR6iYGmMz027LZvmSOSisz1Bk',
    appId: '1:770986243442:ios:621abbb09e33185cf919eb',
    messagingSenderId: '770986243442',
    projectId: 'more-pic',
    storageBucket: 'more_pick',
    iosBundleId: 'com.example.morePic',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDoOq5u0gva0ETKKNNA3vEb048u6p9H4KM',
    appId: '1:770986243442:web:8ea670d409db333ef919eb',
    messagingSenderId: '770986243442',
    projectId: 'more-pic',
    authDomain: 'more-pic.firebaseapp.com',
    storageBucket: 'more_pick',
  );
}
